// places.js
const places = {
    "Aldo's Isle": "/Aldo%27s_Isle",
    "Alessar's Keep": "/Alessar%27s_Keep",
    "Asmodeus' Surf": "/Asmodeus%27_Surf",
    "Asphodel Meadows": "/Asphodel_Meadows",
    "Atlanta's Pool": "/Atlanta%27s_Pool",
    "Avalon": "/Avalon",
    "Bamboo Forests": "/Bamboo_Forests",
    "Baobabs": "/Baobabs",
    "BlackSand": "/BlackSand",
    "Bubonic Beaches": "/Bubonic_Beaches",
    "Battlemage Mountains": "/Battlemage_Mountains",
    "Brown Wizard Delta": "/Brown_Wizard_Delta",
    "Buffkin Plain": "/Buffkin_Plain",
    "Bugbear Boonies": "/Bugbear_Boonies",
    "Calista's Citadel": "/Calista%27s_Citadel",
    "Chroma Crystal Row": "/Chroma_Crystal_Row",
    "Chronomancer's Riviera": "/Chronomancer%27s_Riviera",
    "Cuckoo Land and the Psychic Leap": "/Cuckoo_Land_and_the_Psychic_Leap",
    "Cumberland": "/Cumberland",
    "Donut Atoll": "/Donut_Atoll",
    "Dread Tower": "/Dread_Tower",
    "Duck Alliance Headquarters": "/Duck_Alliance_Headquarters",
    "Elysian Gates": "/Elysian_Gates",
    "Forest of the Imps": "/Forest_of_the_Imps",
    "Fort Turtle": "/Fort_Turtle",
    "Frog Master Marsh": "/Frog_Master_March",
    "Fur Gnome Wold": "/Fur_Gnome_Wold",
    "Ghoulish Boglands": "/Ghoulish_Boglands",
    "Goat Grasslands": "/Goat_Grasslands",
    "Goblin Town": "/Goblin_Town",
    "Great Owl Obelisk": "/Great_Owl_Obelisk",
    "Green Wizard City": "/Green_Wizard_City",
    "Halcyon Sanctum": "/Halcyon_Sanctum",
    "Hall of Cats": "/Hall_of_Cats",
    "Hedge Wizard Wood": "/Hedge_Wizard_Wood",
    "Honor Mountain": "/Honor_Mountain",
    "Hue Master's Pass": "/Hue_Master%27s_Pass",
    "Kelpie's Bay": "/Kelpie%27s_Bay",
    "Kobold's Crossroad": "/Kobold%27s_Crossroad",
    "Lake of Lanterns": "/Lake_of_Lanterns",
    "Lenora's Lighthouse": "/Lenora%27s_Lighthouse",
    "Manticore Valley": "/Manticore_Valley",
    "Mount Titan": "/Mount_Titan",
    "Muscle Mountain": "/Muscle_Mountain",
    "Obsidian City": "/Obsidian_City",
    "Omega Oxbow": "/Omega_Oxbow",
    "Purple Wizard Pavilion": "/Purple_Wizard_Pavilion",
    "Rabbit Lake": "/Rabbit_Lake",
    "Raptor Caye": "/Raptor_Caye",
    "Red Wizard Capital": "/Red_Wizard_Capital",
    "Skylord Rookery": "/Skylord_Rookery",
    "Spirit Villa": "/Spirit_Villa",
    "The Alchemist's Archipelago": "/The_Alchemist%27s_Archipelago",
    "The Bloodfalls": "/The_Bloodfalls",
    "The Brine": "/The_Brine",
    "The Carnival Pass": "/The_Carnival_Pass",
    "The Cave of the Platonic Shadow": "/The_Cave_of_the_Platonic_Shadow",
    "The Court of Chaos Magic": "/The_Court_of_Chaos_Magic",
    "The Dark Sentinel": "/The_Dark_Sentinel",
    "The Fey": "/The_Fey",
    "The Gate to the Seventh Realm": "/The_Gate_to_the_Seventh_Realm",
    "The Infinity Veil": "/The_Infinity_Veil",
    "The Nightmare Dominion": "/The_Nightmare_Dominion",
    "The Quantum Shadow": "/The_Quantum_Shadow",
    "The Salt": "/The_Salt",
    "The Savannah": "/The_Savannah",
    "The Secret Tower": "/The_Secret_Tower",
    "The Slime Pits": "/The_Slime_Pits",
    "The Spike": "/The_Spike",
    "The Toadstools": "/The_Toadstools",
    "The Thorn": "/The_Thorn",
    "The Unicorn Gardens": "/The_Unicorn_Gardens",
    "The Weird House": "/The_Weird_House",
    "The Wild": "/The_Wild",
    "Torment Manor": "/Torment_Manor",
    "Valley of the Void Disciple": "/Valley_of_the_Void_Disciple",
    "Vampyre Mist": "/Vampyre_Mist",
    "White Wizard Tower": "/White_Wizard_Tower",
    "Wolf Dungeon": "/Wolf_Dungeon",
    "Yellow Wizard Haven": "/Yellow_Wizard_Haven",
    "Zaros Oasis": "/Zaros_Oasis",
    "Zomn Valley": "/Zomn_Valley"
  };
  
  export default places;
  