const proppFunctions = [
    { name: "Absence", description: "A member of the hero's community or family leaves the security of the home." },
    { name: "Interdiction", description: "A prohibition or warning is given to the hero." },
    { name: "Violation", description: "The interdiction is violated, often leading to consequences." },
    { name: "Reconnaissance", description: "The villain makes an attempt to gather information." },
    { name: "Delivery", description: "The villain gains information about the victim." },
    { name: "Trickery", description: "The villain attempts to deceive the victim to gain something." },
    { name: "Complicity", description: "The victim is deceived and thereby helps the villain." },
    { name: "Villainy or Lack", description: "The villain causes harm or damage, or a lack or need is established in the story." },
    { name: "Mediation", description: "The hero is made aware of the villainy or lack, often through a call to action." },
    { name: "Beginning Counteraction", description: "The hero decides to take action against the villainy or to address the lack." },
    { name: "Departure", description: "The hero leaves home, embarking on the adventure." },
    { name: "First Function of the Donor", description: "The hero encounters a magical helper or donor, who tests the hero." },
    { name: "Hero's Reaction", description: "The hero responds to the test, often proving worthiness." },
    { name: "Receipt of a Magical Agent", description: "The hero acquires a magical item or assistance." },
    { name: "Guidance", description: "The hero is led to the location of the object of the quest." },
    { name: "Struggle", description: "The hero and the villain engage in direct combat." },
    { name: "Branding", description: "The hero is marked or receives a wound, sometimes leaving a lasting mark." },
    { name: "Victory", description: "The villain is defeated." },
    { name: "Liquidation", description: "The initial lack or villainy is remedied, restoring order." },
    { name: "Return", description: "The hero returns home." },
    { name: "Pursuit", description: "The hero is pursued by the villain or by someone seeking vengeance." },
    { name: "Rescue", description: "The hero is rescued from the pursuit or overcomes the pursuit." },
    { name: "Unrecognized Arrival", description: "The hero arrives home or in another place unrecognized." },
    { name: "Unfounded Claims", description: "A false hero presents unfounded claims, trying to take credit for the hero's actions." },
    { name: "Difficult Task", description: "A difficult challenge or task is proposed to the hero." },
    { name: "Solution", description: "The hero solves the task or challenge." },
    { name: "Recognition", description: "The hero is recognized, often through a mark, token, or other distinguishing feature." },
    { name: "Exposure", description: "The false hero or the villain is exposed." },
    { name: "Transfiguration", description: "The hero is given a new appearance or elevated status." },
    { name: "Punishment", description: "The villain is punished." },
    { name: "Wedding", description: "The hero marries and ascends to the throne or gains some reward." }
  ];
  export default proppFunctions